### ISSUE TITLE
Tournament API Functions are available only on Production Keys

### ISSUE THREAD

**Issue by regiszanandrea** [dolejska-daniel/riot-api#10]
Hi, 

I was reading your docs and here: https://github.com/dolejska-daniel/riot-api/wiki/LeagueAPI:-Resources-and-endpoints#tournament---tournament-stub- 

I saw this phrase: 

> Only these functions are available in interim mode

I think, the correct way is:

_"Only these functions are **not** available in interim mode"_. Because, we only have access to Tournament API with a production key.

Am I correct?

Best regards.

**Comment by dolejska-daniel** [comment]
Hello @regiszanandrea, you are not perfectly correct:

When you send your app's application for TournamentAPI key, you won't get production key right away, so what they do is basically this - they will give you a key, with which you can use TournamentAPI **but only it's stub endpoint** since it's in `interim mode` by default (until you prove you have your project ready, answer some questions and they finally approve your key for production).

So when they completly approve your application, they change your API key's mode from _interim_ to _production_ and then and **only then** you can use "real" (production, non-stub) TournamentAPI endpoints.

Also, not all endpoints available on production TournamentAPI resource are available in TournamentAPI stub resource - thats why I've said that only listed functions are available in `interim mode`. Whole point of interim mode in this library is that **it doesn't change a thing for you when you migrate from dev to production** (stub/interim endpoints to production endpoints) , only except you can't use all of the methods when in `interim mode`, you just set `interim mode` to `false`.

Let me know whether this answer is okay or not 😄,
Daniel

**Comment by regiszanandrea** [comment]
Oh, now I can see. This answer made me very clear about this issue. 

Thanks for your detailed explanation and this package, it's having been very helpful.

Best regards,
Regis.

**Comment by regiszanandrea** [comment]
Hi @dolejska-daniel, do you know how I can get the interim mode key? I applied to an application and they understood that I was applying to a Production key. :(

**Comment by dolejska-daniel** [comment]
Hello,

you are always applying for a production key. But if your project is not complete you will first receive interim code.

Better askt them than me :smile:

**Comment by regiszanandrea** [comment]
Yeah, I was reject but I didn't receive any key. 

I already asked them, but thanks for the answer.

**Comment by dolejska-daniel** [comment]
I guess you should not receive any key if your app was rejected :smile:

2018-03-01 13:39 GMT+01:00 regiszanandrea <notifications@github.com>:

**Comment by regiszanandrea** [comment]
Ok I agree, but this development key returns the error: invalid key on Tournament Stub API: https://we.tl/YXS24m1ngE I don't know what to do :(

**Comment by dolejska-daniel** [comment]
Because this one is your main development key which does not have access to
Tournament Stub API (only to all normal ones).

Riot guys have to first approve your application and explicitly give you
Tournament API key, which has the permission to make calls to these
endpoints.

**Comment by regiszanandrea** [comment]
So, We have be approved and them we can have access to Tournaments API?

**Comment by dolejska-daniel** [comment]
Exactly. You must be approved for interim mode access to Tournament API.

**Comment by regiszanandrea** [comment]
Thanks a lot again @dolejska-daniel .
