### ISSUE TITLE
[Question] Is there a way to get the champion's icon without wrapping it in an image element?

### ISSUE THREAD

**Issue by zaclummys** [dolejska-daniel/riot-api#16]
I'd like to get the full address of the static files.

**Comment by dolejska-daniel** [comment]
Hello @zaclummys,

it is not currently possible to retrieve _only_ image URL, **but** it is possible to easily extract it from generated [`Html`](https://github.com/dolejska-daniel/riot-api/blob/master/src/DataDragonAPI/Utils/Html.php) class instance. Heres how:

**Source**:
```php
DataDragonAPI::initByCdn();
var_dump(DataDragonAPI::getChampionLoading('Orianna')->getAttribute('src'));
```

**Output**:
```
string(73) "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Orianna_0.jpg"
```

I will add functions, that will only generate image URLs, also supporting SSL as soon as I get to it. Thank you for your question - if you've got any more questions, feel free to ask, otherwise, mark this issue as closed.

Daniel

**Comment by dolejska-daniel** [comment]
Hi there again,

you can now refer to [`v2.0.0-rc.4`](https://github.com/dolejska-daniel/riot-api/releases/tag/v2.0.0-rc.4)([`299599c`](https://github.com/dolejska-daniel/riot-api/commit/299599c649584bad180adac7996d76224679465c)), it should contain what you've asked for 😺.

**Comment by zaclummys** [comment]
I have an suggestion.

Create a new method called `RiotAPI::region` to create a new instance with same settings but different region setting.

```php
class RiotAPI {
    // ...
    public static region (RiotAPI $instance, Region $region) {
        $settings = clone $instance->settings; // clone all settings

        $settings[
            RiotAPI::SET_REGION => $region, // change region setting
        ];

        return new RiotAPI(settings); // return a new instance
    }
}

$RiotAPINorthAmerica = new RiotAPI([
    RiotAPI::SET_KEY => '',
    RiotAPI::SET_REGION => Region::NORTH_AMERICA,
]);

$RiotAPIBrazil = RiotAPI::region($RiotAPINorthAmerica, Region::BRAZIL);

// or

$RiotAPI = new RiotAPI([
    RiotAPI::SET_KEY => '',
]);

$RiotAPIBrazil = RiotAPI::region($RiotAPI, Region::BRAZIL);
```

**Comment by dolejska-daniel** [comment]
Hi again @zaclummys,

I don't see a reason, why would that be useful. You can easily change current region with `RiotAPI::setRegion(...)` or change it only temporarily using `RiotAPI::setTemporaryRegion(...)` with ability to revert it to the previous region setting using `RiotAPI::unsetTemporaryRegion()`.

Tell me when you would need to create completly new instance with only different region settings, even when you've got the ability to change it during its lifetime.

Daniel

**Comment by zaclummys** [comment]
@dolejska-daniel,

You're right! I hadn't noticed `RiotAPI::setTemporaryRegion(...)`. 

That method solves my problem. Thank you!

**Comment by zaclummys** [comment]
@dolejska-daniel,

I tested some endpoints and got another suggestion.

`/lol/static-data/v3/champions/{id}` can only be requested 10 times a hour (10:3600). It's not feasible to use it that way.

Some rioters recommend getting the entire list and caching it instead of getting items individually. (https://discussion.developer.riotgames.com/questions/3204/why-am-i-getting-statusmessagerate-limit-exceededs.html)

I think a many-to-one caching system can solves that.

```
/lol/static-data/v3/champions/1 +----+
                                     |----+ /lol/static-data/v3/champions
/lol/static-data/v3/champions/2 +----+
```

What do you think about it?

**Comment by dolejska-daniel** [comment]
Hey, @zaclummys,

the idea behind is this great, but this type of change made to the function accessing `/lol/static-data/v3/champions/{id}` endpoint would result in endpoint being completly inaccessible by the library - it would instead of that endpoint use data from different endpoint.

Because if the functionality of the port would eventually change in the future or if someone would _really want to actually use the endpoint_, **they would not be able to**.

People are not dummies, so when using StaticData, they will implement this on their side (eventually 😆, when they notice the low limit on StaticData endpoints). Anyhow, this approach is used in [StaticData linking](https://github.com/dolejska-daniel/riot-api/wiki/LeagueAPI:-StaticData-linking) feature, so whatever for would someone want to use the mentioned endpoint, they don't actually really need to, when they can use StaticData linking with any request made to the API.

Also, next time, please make sure to create new issue, this idea is not really related to the current issue topic and since we've solved this, I'll mark it as closed 😺.

Daniel
