### ISSUE TITLE
Getting match stats without performing a massive amount of requests

### ISSUE THREAD

**Issue by xKairu** [dolejska-daniel/riot-api#2]
Hey, I'm looking for a library to replace leaguewrap for v3 coming up, and this one looks nice. I just have one issue so far:

with leaguewrap, I can do `$matches = $api->game()->recent($summoner)`, and it'll give me the stats for those matches on `$matches[0]->stats`.

With this, I would need to pull in the recent match list, then make a request to pull in the MatchDto for each match, then each match I need to pull in 10 ParticipantDto objects, then for each of those, I need a ParticipantStatsDto object, and even then, I have no way of checking which ParticipantDto object is the one for the user I'm actually requesting. At the moment, I can't even pull in the MatchDto objects before hitting my rate limit, let alone a potential 421 (i think) requests for data that I need up front.

Is this a limitation of the v3 API, or just the library? Maybe I'm just reading it all wrong.

Thanks.

**Comment by dolejska-daniel** [comment]
Hello @xKairu, thank you for your interest in this library!

I am kind of happy to tell you, that you are actually reading it _kind of_ wrong, but there are big changes for you probably. Yet you do not need to fetch these objects separately, all these objects are returned when the call is made:

To get access to stats for recent matches, all you have to do is this:
```php
$matches = []; // array for fetched matches
$matchlist = $api->getRecentMatchlistByAccount($account_id); // not SummonerID!
foreach ($matchlist->matches as $game) // for each recent match
    $matches[] = $api->getMatch($game->gameId); // fetch the match with stats, timeline, etc.
```
..because stats are part of MatchDto object returned by `$api->getMatch()`. You can access them just like this:
```php
$m = $matches[0]; // first fetched match
$summoner = $m->participantIdentities[0]->player; // identity of first participant - id, name...
$stats = $m->participants[0]->stats; // stats for the first participant
```

**Your true problem is here**: As per newly introduced policy for ranked vs. non-ranked games, _you won't be able to know which participant is which in normal game_. Non-ranked games (normal draft, blind, aram, etc.) are now private only, and only ranked games are public.
You can read more about this at https://developer.riotgames.com/policies/data-policies.html.

So ultimately, when you fetch data of normal game, your `$match->participantIdentities` is going to be `NULL`, but stats will be there, you just won't know, which are whose. `participantIdentities` will be set only when the match happens to be a ranked game.

**Comment by xKairu** [comment]
I just had a bit of a dig around and seem to have figured it out, so it's not as bad as I had initially thought.

Issue 1 now is differentiating between queues, modes and types. I'm not very familiar with LoL, I'm just a filthy FPS player. I was testing with data from C9 Sneaky, and got a queue of 420, mode of CLASSIC, and a type of MATCHED_GAME. Does this sound right? I would imagine that's just a standard ranked game? I have no idea what a queue is, but mode and type seem pretty straight forward.

Issue 2 is getting the constants for roles and lanes. I have currently have:

```
abstract class PlayerPosition
{
    const TOP = 'TOP';
    const MID = 'MIDDLE';
    const JUNGLE = 'JUNGLE';
    const BOT = 'BOTTOM';
}
``` 

```
abstract class PlayerRole
{
    const DUO = 'DUO_CARRY';
    const SUPPORT = 'DUO_SUPPORT';
    const CARRY = 'AD_CARRY';
    const SOLO = 'SOLO';
    const NONE = 'NONE';
}
```

For Role, I found all but CARRY in Sneaky's games, so I just assumed what it would be, and I don't know if the other ones are even correct, as "duo carry" and "duo support" don't sound right, in my limited knowledge of the game. In the v2 API, these were just integers.

Everything else sounds about perfect though. After a bit of digging, this is much, much nicer to work with than leaguewrap. Thanks.

**Comment by dolejska-daniel** [comment]
You can find the constants used in API's results on this page with description of their meaning https://developer.riotgames.com/game-constants.html. Sadly, position-role combinations are not there, but `DUO_SUPPORT` ad `DUO_CARRY` is alright.

As a played I'd assume, that it should look like this:

| Position | Roles |
| --------- | ------ |
| `TOP` | `SOLO` |
| `MID` | `SOLO` |
| `JUNGLE` | `NONE` |
| `BOT` | `DUO`, `DUO_CARRY`, `DUO_SUPPORT`  |

_But I'd guess, that when someone will play non-standard lanes, you can end up with something like `BOT`-`SOLO` or even `BOT`-`NONE`. But that is just a guess._

Also, thank you for the feedback on the library! If you'd find any bugs, things you would not understand or things that could be improved, I'll gladly assist 😺.

Feel free to reopen this issue or create new one at any time 🙂.
