### ISSUE TITLE
Data Dragon Update

### ISSUE THREAD

**Issue by boraguler** [dolejska-daniel/riot-api#20]
I'm newbie on RIOT API, just got your beautiful work and started to work with it, thank you very much.

About Data Dragon, seems Riot cut off static api, now API returns "Request: Forbidden. (Forbidden)" messages for most Data Dragon calls. 

Will you be able to update soon?

**Comment by dolejska-daniel** [comment]
Hello and thank you for using this library 😃 I hope it works well for you.

I will try to implement workaround for StaticData deprecation for both DD & RiotAPI ASAP. I guess I will manage this week. We will see 😆...

**Comment by boraguler** [comment]
Thank you very much.

By the way, I'm using a shared hosting. I had to add new doctrine/inflector version in composer manually, since it was giving errors when I uploaded to live. Just a reminder. /cheers

**Comment by dolejska-daniel** [comment]
Hey @boraguler,

what exactly does not work on DD API for you? I think that DD API went without changes during StaticData deprecation.. 🤔

**Comment by boraguler** [comment]
for ex. when i try the same with your example on [here](https://github.com/dolejska-daniel/riot-api/wiki/DataDragonAPI%3A-Usage-example#using-riotapi-objects)

**Comment by dolejska-daniel** [comment]
Okay -- that is actually not problem of DataDragon API itself, that is a problem of RiotAPI (due to StaticData endpoint deprecation).

**Comment by dolejska-daniel** [comment]
@TheKeymaster It's not there yet, I'll try to look into it today. I'm currently quite busy with my Bachelor's thesis and other school projects :weary:. I'm sorry it's taking this long.

**Comment by TheKeymaster** [comment]
@dolejska-daniel thanks for your quick response and fix! 
Just for your information; I can't get the latest version from packagist. I need to use `composer require dev-master` to get the latest version. 
Could you create a new version on packagist as well? That would be great!

**Comment by dolejska-daniel** [comment]
I've created release [v2.0.1](https://github.com/dolejska-daniel/riot-api/releases/tag/v2.0.1) anyways 😆. Just for you 😎.

**Comment by TheKeymaster** [comment]
Thank you!!

**Comment by regiszanandrea** [comment]
Hey @dolejska-daniel ,

There will be a new version of this library for Riot API v4?

Thanks

**Comment by dolejska-daniel** [comment]
Hi @regiszanandrea,

I haven't looked into that just yet - so I do not know the number of differences between these versions. What do you mean by "will there be a new version"? As if I bring this library up-to date? If this is the question then probably yes.

...thought to get some help would be awesome, since I am working on my Bachelor's Thesis :smile_cat:.

**Comment by regiszanandrea** [comment]
Yeah, if you bring this library up-to date.

This is the official announcement: https://discussion.developer.riotgames.com/articles/6579/player-universally-unique-identifiers-and-a-new-se.html

I could help in developing something, because I'm using this library every day in a project. So if you need something you can email me at regiszanandrea@gmail.com

**Comment by dolejska-daniel** [comment]
I will do my best and I'll try to update it but I cannot tell you when I'll have enough time for it right now.

**Comment by dolejska-daniel** [comment]
Hey guys, I am quite pleased to tell you, that StaticData calls are once more available through RiotAPI!

**Comment by dolejska-daniel** [comment]
@boraguler @TheKeymaster @regiszanandrea,
I'll close this issue since it is solved by new [v3.0.0-rc.1](https://github.com/dolejska-daniel/riot-api/releases/tag/v3.0.0-rc.1) release. Please make sure to check out [important changes in `v3`](https://github.com/dolejska-daniel/riot-api#riotapi-v3-changes-warning) so you won't have hard time updating 😼.

Any feedback is well appreciated! 😺
