### ISSUE TITLE
Player object within ParticipantIdentity is null

### ISSUE THREAD

**Issue by xKairu** [dolejska-daniel/riot-api#4]
Game ID for example: 2544947953

```
$api = new RiotAPI([
  RiotAPI::SET_KEY => config('services.riot.key'),
  RiotAPI::SET_REGION => Region::NORTH_AMERICA,
]);

$summoner = $api->getSummonerByName('tking295');
$matches = $api->getRecentMatchlistByAccount($summoner->accountId)->matches;
$match = $api->getMatch($matches[0]->gameId);
dd($match);
```
And as you can see, all the `player` objects are null, so I can't check the accountId with my current Summoner object. https://gist.github.com/xKairu/e53df42f8bfbe798f79036f3f591c955

At first I thought this might be because of a live game, but lolking has no problem viewing this match and it was 8 hours ago. Is this normal with the new API?

**Comment by dolejska-daniel** [comment]
Hello @xKairu,

if I understand your problem correctly I've mentioned this problem in the first issue (#2) you've created:

> As per newly introduced policy for ranked vs. non-ranked games, you won't be able to know which 
 participant is which in normal game. Non-ranked games (normal draft, blind, aram, etc.) are now private only, and only ranked games are public.

You can read more about this at https://developer.riotgames.com/policies/data-policies.html.

`ParticipantIdentities` are going to be `null` because __you are not allowed to know__, which player is which __in non-ranked games__.

Hope this is what you've asked 😺. Also sorry for the late response, I've been on vacation last two weeks.

**Comment by xKairu** [comment]
Oh, so these matches are non-ranked? That makes my life a bit easier. Thanks for putting up with the constant questions lmao.
