### ISSUE TITLE
Paypal, Twitter and Guzzle

### ISSUE THREAD

**Issue by SeaRoth** [dolejska-daniel/riot-api#5]
I just downloaded this library today, thank you very much for it! I am migrating my old league stats app and this seems like a solid option for a wrapper. So far it works flawlessly!

The author of this library should consider adding a Paypal donation button at the bottom of project if he/she isn't rich yet and they should also add their Twitter handle in case anyone wants to network (not necessarily ask questions). 

This is my first time using Composer - I am receiving this error at the end of composer update:

> Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.

- I am going to ignore this for now - I'm not really sure if it matters and I'm sure you've already come across this

![image](https://user-images.githubusercontent.com/3461713/29181051-93594f68-7dae-11e7-8c77-f73d37e70c3d.png)

**Comment by dolejska-daniel** [comment]
Hello @SeaRoth,

thank you very much for sharing your experience with the library. I'm happy that it serves well. I will consider adding buttons you've mentioned - Twitter won't be a problem and I can add PayPal as well because I sure am not rich yet 🤣.

Back to Guzzle - I am not using the Guzzle library, some of the dependencies are using it. I think that only way to get rid of the warning is when the dependency author updates it in their project. Anyhow I'll check on that.

BUT you could probably get rid of it by not installing **dev dependencies**. You can do that by using `composer install --no-dev`. My only dev dependencies are _phpunit_ for tests, and _codeclimate test reporter_, you do not need them for the library to work.

I'll check about the Guzzle and update you soon! 😸

**Comment by dolejska-daniel** [comment]
Hi again @SeaRoth,

so, as I thought, library [satooshi/php-coveralls](https://packagist.org/packages/satooshi/php-coveralls) (used by library for CodeClimate test coverage reporting [codeclimate/php-test-reporter](https://packagist.org/packages/codeclimate/php-test-reporter)) is on its newest stable version using old Guzzle package.

But - the warning you mentioned does not affect function of the library in any way. So you do not need to worry about it at all. And as I've said, you can get rid of it by using option `--no-dev` when installing the packages with Composer.

Feel free to close the issue if there is not anything else on your mind 😃

**Comment by SeaRoth** [comment]
Thank you very much!  There is nothing else on my mind right now except finishing this app!  You will very likely hear from me again! Cheers mate!
