### ISSUE TITLE
Rate Limits & Caching

### ISSUE THREAD

**Issue by SeaRoth** [dolejska-daniel/riot-api#6]
Please pardon my noobness,

I was reading this [closed bug ](https://github.com/dolejska-daniel/riot-api/issues/3) and trying to grasp how to do rate limits and caching calls but I'm just completely lost.

Do I need to make my own cache provider class that connects to my database and then uploads / retrieves the data from there? Should I follow [this](https://laravel.com/docs/5.4/cache) to set it up? Should I just copy/pasta [xKairu's ICacheProvider](https://gist.github.com/xKairu/ede67698327fb722aea5e14bbd21fc68)?

I'm about to implement the next level to my app which will make 10-20 requests for the match data and I neither want to go over the rate limit nor do I want to continually ask Riot for the information when I could just as easily store it into a SQL database or where ever.

**Comment by dolejska-daniel** [comment]
Hello again @SeaRoth,

regarding the closed issue (#3) - the information in there _is already outdated_, now all you need to do in order to enable rate limiting is to provide `RiotAPI::SET_CACHE_RATELIMIT` option with `true` value when initializing the library. That's how easy it is now, the process is fully automatic and you do not need to provide the limits by yourself anymore.
_For further info on rate limiting, please visit [wiki pages](https://github.com/dolejska-daniel/riot-api/wiki/LeagueAPI:-Rate-limiting)._

And the caching - that's more like about what you would prefer. If you'd like some sort of SQL cache provider, you will have to implement it by yourself (because I did not make one). But if you are using Laravel, then, I guess you can use xKairu's cache provider for Laravel.
_For further info on caching providers, please visit [wiki pages](https://github.com/dolejska-daniel/riot-api/wiki/LeagueAPI:-Cache-providers)._

Regarding the match data, `Match resource` is not really suitable for [call caching](https://github.com/dolejska-daniel/riot-api/wiki/LeagueAPI:-Call-caching), library would cache match endpoints for each match but it would also cache matchlist endpoints, which would prevent you from accessing new matches from match history.
For this purpose, saving the data to database is probably the best option.

If you've got any more questions or if anything from what I've explained is still unclear, feel completly free to reply anytime or to close the issue 😼

**Comment by SeaRoth** [comment]
Ello M8!

Ok I'm gonna go into uncharted territory and get this SQL caching (or a json version) to work and hopefully contribute.

- Do you have a league app? 
- How do you prevent the app from requesting the same info over and over (e.g. match DTO, static champion data)? 
- What if you go over the rate limit, do you tell the user to wait 10 seconds and try again? Do you add a loading gif and tell the users to wait while it finishes?

While testing your own app - it's SO easy to exceed the rate limits:
1. getStaticChampions()
2. getStaticItems()
3. getStaticMasteries()
4. getStaticRunes()
5. getStaticSummonerSpells()
6. getSummonerByName()
7. getRecentMatchlistByAccount()
8. getMatch() * 20

Have you ran into such a problem? How did you get around it?

**Comment by dolejska-daniel** [comment]
_Do you have a league app?_
**A:** I kind of do have, but I am only using tournament endpoints, so I do not actually need to cache anything. I do not need to work with match history of the player, BUT I am saving the match data in my database, when the game ends.

_How do you prevent the app from requesting the same info over and over (e.g. match DTO, static champion data)?_
**A:** I just enable the ratelimiting feature.

_What if you go over the rate limit, do you tell the user to wait 10 seconds and try again? Do you add a loading gif and tell the users to wait while it finishes?_
**A:** Yeah, probably, there is not really another way around it, just use this:
```php
// ...
try {
    $api->getMatch(...);
}
catch (ServerLimitException $ex) {
    // Ratelimit exceeded, handle this state
}
// ...
```

_While testing your own app - it's SO easy to exceed the rate limits_
**A:** Yeah, I know about these, but its important to know, that __there are two limits__ in place:
    1. **API Key Limit** - that is the limit of your _specific key_ (lower when its development key, higher when its production key)
    2. **Method Limit** - this is the limitation on the side of the API, it limits calls per function (endpoint) per key. This means that even when you wouln't have exceeded your **key limit** you can exceed method limit by calling the method over and over again.

_Method limits_ were **recently** introduced to the StaticData resource, and they are VERY strict in comparison to the limits for other endpoints. For further information on rate limiting and rate limits itself, you can visit [official Riot developer pages](https://developer.riotgames.com/rate-limiting.html).

How to get around these... you need to use cache. __TIP__ - method rate limits are not region enforced, which means when you deplete method rate limit on EUNE, you can continue on EUW, TR, NA, etc. (you can use this workaround when fetching previously mentioned StaticData, but obviously not when trying to get someones matchhistory).
