### ISSUE TITLE
Package not working with symfony/console v5

### ISSUE THREAD

**Issue by RensBruil** [dolejska-daniel/riot-api#79]
With laravel version 7.6.1, Symfony/Console is installed within the package. It seems that your package requires Symfony/Console v4 to operate?

Version 3 of your package works fine though, its only when using 4.0+

Console output in attachments
![401f58215c8d572028b03daba34030b7](https://user-images.githubusercontent.com/1311928/79247875-5b88f180-7e7b-11ea-8420-a7fde1cbed7f.png)

**Comment by dolejska-daniel** [comment]
Hello @RensBruil, thank you for your interest in this library! Latest Laravel version is 7.3, not 7.6, isn't that right?

**Comment by RensBruil** [comment]
Hi, @dolejska-daniel ,

You are right about the Laravel version. What I had to do is formulate is better. Laravel requires: https://packagist.org/packages/laravel/framework. This package is currently on v7.6.1, and requires symfony/console: ^5.0. 

Which means that your package is not available when using the latest version of Laravel, think updating the package list for Console v5 will solve the issue?

**Comment by dolejska-daniel** [comment]
Alright -- my bad! All this time I thought that `symfony/console` in version `5` is allowed, but no version has been published with the fix (it has been fixed by d7d0d38fa5d12b0ed409774f3e3eff2f2f4ccbad).

Anyway - I've pushed new version with latests fixes to Packagist. Try pulling latest version via Composer.
