### ISSUE TITLE
STATICDATA LINKING

### ISSUE THREAD

**Issue by Tiposbingo** [dolejska-daniel/riot-api#8]
Hi there, 

please help, if I use this :
`
$api = new RiotAPI([ RiotAPI::SET_STATICDATA_LINKING => true,]);
`
show me this always http://take.ms/Cct3C problem with rate limit :/

**Comment by dolejska-daniel** [comment]
Hello,

thank you for reporting this. This is probably bug from time, when calls to static-data endpoint were not limited. I will look into this issue as soon as I can.

**Comment by dolejska-daniel** [comment]
@Tiposbingo hello again,

this problem should now be fixed in 62cbfb8. StaticData linking feature now __requires__ call caching to be enabled (this is mainly because of strict and low limits on StaticData resource by Riot, otherwise you'd be able to make a few requests with linked StaticData and then you'd bump into the rate limit problem again).
