### ISSUE TITLE
Features Update

### ISSUE THREAD

**Issue by New-on-Git** [dolejska-daniel/riot-api#99]
Hi, i've been looking at your library and it's really nice to use ! 
Quite simple and it has a lot of ressources from riot's Database. 

But few things seems to be deprecated, especialy Stats and Masteries. Do you think you'll be able to update those ?

I'm looking to create a web application on the same page of op.gg and those things are essentials to me. Your library seems to be quite perfect for me, this apart.
Otherwise do you think it's possible to update /recreate those myself ? 
Thanks a lot

**Comment by dolejska-daniel** [comment]
Hello! Thank you for your kind words 😊 If you refer to the endpoints shown in the table in README, then I will have to disappoint you — the endpoints with `deprecated` state have been deprecated by Riot's API team, not by me.

**Comment by New-on-Git** [comment]
Oh okay but there is no way to get them back again ? I mean, Riot's changed there way to get those data, but it's still possible to get them right ?

**Comment by New-on-Git** [comment]
![stats](https://user-images.githubusercontent.com/77384850/104486801-8fd93c00-55cc-11eb-9afb-536cd2d49f2d.JPG)

I took a look at riot's DataBase and it seems that stats are now here.

( i feel like i'm giving advices and shit but hell no, sorry if it sounds like it, i'm just a beginner in PHP and i'm trying to see though all of this and speaking about it helps me a lot)

**Comment by dolejska-daniel** [comment]
No, the `Stats` endpoint and the data it has provided has been deprecated for good and there is no way to get that back, on the contrary, nothing is stopping you from getting such information yourself - fetching lots of matches and aggregating the statistics yourself.
The `Masteries` and `Runes` endpoints have been deprecated because there is no such thing as masteries or runes anymore in the game - this has been replaced by `RunesReforged` when this feature has been released a few years back.

**Comment by New-on-Git** [comment]
Oh okay, i though `Stats` gathered player's the win rate and win rate per champions.
Thanks a lot for those explanations :)

**Comment by dolejska-daniel** [comment]
Happy to be of help :) Historically the `Stats` endpoint provided all sorts of (even long-term) statistics not limited to win rates. Anyway, if your questions have been answered, please close your issue as solved 👍🏽
